# Generated by Django 5.0 on 2023-12-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='br',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='cont',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='qrcode_id',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='reworked',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='email',
            new_name='verification',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
    ]
